# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18f25bac0dfdbdbdb4c3ee4473fbf8913300b80997d06ec4ad7785d136a9e6aba00533f552f3f51d424046ca38cc7252bac31a9122b0a2efd48e6651555fa51d

test:
  secret_key_base: 90e6642cae97f92c6e6cce7b6f315e53b4fb4782db0f21adaa2b5f9c50ff822913139cc7e9b944ab29bf8e0d19c216a130a02f6d3b345cc50f1429aac1b8bdb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
